export const actions = {
  ADD_BOOK: "ADD_BOOK",
  LOADING_BOOK: "LOADING_BOOK",
  PAGINATION_BOOK: "PAGINATION_BOOK",
  GET_BOOKS_INFO: "GET_BOOKS_INFO",
  FILTER_BOOKS_INFO: "FILTER_BOOKS_INFO",
  ERROR_REQUEST: "ERROR_REQUEST",
};
